/* $Id: rex_util_help.h,v 1.1 2021/08/31 21:03:27 alex Exp $ */
/*******************************************************************************

    rex_util_help.h

    Regular Expression Utility Help Text.


    This is help text for use by programs that need to display information
    about REX_UTIL regular expressions and substitution.  For example, the
    "-help" command-line option to my CHAFN and TREX programs output this
    text to the user's console.

    The text is a sequence of character strings, each enclosed in a
    REX_HELP_LINE macro.  REX_HELP_LINE can be #define'd in various ways.
    To print out the help text on the user's console, within the program
    do the following (this is executable code):

        #define  REX_HELP_LINE(s)  printf ("%s\n", s) ;
        #include  "rex_util_help.h"

    NOTE that the character strings do not end with newline characters.
    To initialize an array of character strings containing the help text:

        #define  REX_HELP_LINE(s)  s,

        static  const  char  *RexUtilHelp[] = {
        #    include  "rex_util_help.h"
            NULL
        } ;

    If REX_HELP_LINE is not #define'd, this header file uses the above
    definition for an array of strings.

    In all cases, REX_HELP_LINE is #undef'ed at the end of the header file.
    An application must redefine REX_HELP_LINE if it needs to include this
    header file again in the same source file.

    The sequence of REX_HELP_LINE-enclosed strings is generated by the
    Makefile from "rex_util_help.txt".  The sequence is written to
    "rex_util_help.h.new", which can then replace -- manually via editing --
    the sequence below in this version-controlled file.

*******************************************************************************/


#ifndef REX_HELP_LINE
	/* Construct a list of character strings for initializing an array. */
#    define  REX_HELP_LINE (s)  s,
#endif

REX_HELP_LINE ("Basic RE Symbols:")
REX_HELP_LINE ("")
REX_HELP_LINE ("    c       matches character c.")
REX_HELP_LINE ("    \\c      matches character c.  Escaping c in this way allows")
REX_HELP_LINE ("            matching a literal character c when c is an RE special")
REX_HELP_LINE ("            symbol.  For example, \"(\" is a special symbol indicating")
REX_HELP_LINE ("            the start of an RE group and doesn't actually match any")
REX_HELP_LINE ("            character itself.  However, \"\\(\" has nothing to do with")
REX_HELP_LINE ("            groups and matches a literal left parenthesis in the")
REX_HELP_LINE ("            target text.")
REX_HELP_LINE ("    .       matches any character.")
REX_HELP_LINE ("    ^  $    anchor the match at the beginning and end of the line,")
REX_HELP_LINE ("            respectively.  Aside from appearing at the very")
REX_HELP_LINE ("            beginning and at the very end of the complete RE,")
REX_HELP_LINE ("            these anchors can also be used with the same meanings")
REX_HELP_LINE ("            in alternation expressions; for example, \"^abc|^def$\".")
REX_HELP_LINE ("")
REX_HELP_LINE ("Quantified regular expressions:")
REX_HELP_LINE ("")
REX_HELP_LINE ("    RE*     matches zero or more instances of the RE.")
REX_HELP_LINE ("    RE+     matches one or more instances of the RE.")
REX_HELP_LINE ("    RE?     matches zero or one instance of the RE.")
REX_HELP_LINE ("    RE{m}   matches exactly M instances of the RE.")
REX_HELP_LINE ("    RE{m,n} matches between M and N instances of the RE.")
REX_HELP_LINE ("")
REX_HELP_LINE ("Concatenation and alternation:")
REX_HELP_LINE ("")
REX_HELP_LINE ("    RE1RE2  matches RE1 followed immediately by RE2 (no intervening")
REX_HELP_LINE ("            spaces in the RE patterns or in the target string).")
REX_HELP_LINE ("    RE1|RE2 matches RE1 or RE2.")
REX_HELP_LINE ("")
REX_HELP_LINE ("Grouping:")
REX_HELP_LINE ("")
REX_HELP_LINE ("    (RE)    allows grouping of RE's.  These subexpressions also")
REX_HELP_LINE ("            function as capture groups, the indices of which are")
REX_HELP_LINE ("            automatically assigned according to the order of the")
REX_HELP_LINE ("            left parentheses.  The indices begin with 1 and there")
REX_HELP_LINE ("            is no limit on the number of groups, memory permitting.")
REX_HELP_LINE ("    (?<name>RE)")
REX_HELP_LINE ("            assigns a name, enclosed in angle brackets, to a")
REX_HELP_LINE ("            capture group.  In replacement and substitution,")
REX_HELP_LINE ("            the capture group can be referenced by index or name.")
REX_HELP_LINE ("    (?:RE)  specifies a non-capture group.  The group has no index")
REX_HELP_LINE ("            and cannot be referenced in substitution strings.  Its")
REX_HELP_LINE ("            simple purpose is grouping REs.")
REX_HELP_LINE ("")
REX_HELP_LINE ("Special Character Sequences:")
REX_HELP_LINE ("")
REX_HELP_LINE ("    \\xHH    matches the character with the given 2-digit,")
REX_HELP_LINE ("            hexadecimal value.")
REX_HELP_LINE ("    \\uHHHH  inserts the 1 to 4 characters of the UTF-8 representation")
REX_HELP_LINE ("            of Unicode code point U+HHHH.  This is for code points in")
REX_HELP_LINE ("            the Basic Multilingual plane, U+0000 through U+FFFF.  The")
REX_HELP_LINE ("            code point must be specified as 4 hexadecimal digits.")
REX_HELP_LINE ("    \\UHHHHHH")
REX_HELP_LINE ("            inserts the 1 to 4 characters of the UTF-8 representation")
REX_HELP_LINE ("            of Unicode code point U+HHHHHH.  This is for code points")
REX_HELP_LINE ("            in any of the 17 Unicode planes; the code points range")
REX_HELP_LINE ("            from U+000000 to U+10FFFF.  6 hexadecimal digits must")
REX_HELP_LINE ("            be specified.")
REX_HELP_LINE ("    \\u{HHH...}")
REX_HELP_LINE ("            specifies a Unicode code point with a variable number of")
REX_HELP_LINE ("            hexadecimal digits.")
REX_HELP_LINE ("    \\d      matches a decimal digit, '0' to '9'; equivalent to \"[0-9]\".")
REX_HELP_LINE ("    \\D      matches anything but a decimal digit, '0' to '9'.  Equivalent")
REX_HELP_LINE ("            to \"[^[:digit:]]\".")
REX_HELP_LINE ("")
REX_HELP_LINE ("Character Classes (Outer Square Brackets):")
REX_HELP_LINE ("")
REX_HELP_LINE ("    [...]   matches classes of characters between the square brackets.")
REX_HELP_LINE ("    [^...]  matches anything but the classes of characters.")
REX_HELP_LINE ("")
REX_HELP_LINE ("Character Classes (Within the Outer Square Brackets):")
REX_HELP_LINE ("")
REX_HELP_LINE ("    c-c     matches any character in a range of characters.  Any")
REX_HELP_LINE ("            number of these ranges may be specified between the")
REX_HELP_LINE ("            square brackets or between the complementing caret")
REX_HELP_LINE ("            and the right square bracket.  For example, \"[123a-z45]\"")
REX_HELP_LINE ("            matches the numbers '1', '2', '3', '4', and '5' and the")
REX_HELP_LINE ("            lower-case English alphabet (letters 'a' through 'z').")
REX_HELP_LINE ("    c       matches the specified character; e.g., \"[aeiou]\" matches a vowel.")
REX_HELP_LINE ("    [:class:]    -- must appear inside [...] or [^...]")
REX_HELP_LINE ("            matches an ASCII character in the specified class:")
REX_HELP_LINE ("                [:alnum:]    [:digit:]    [:space:]")
REX_HELP_LINE ("                [:alpha:]    [:graph:]    [:upper:]")
REX_HELP_LINE ("                [:ascii:]    [:lower:]    [:xdigit:]")
REX_HELP_LINE ("                [:blank:]    [:print:]    [:word:]")
REX_HELP_LINE ("                [:cntrl:]    [:punct:]")
REX_HELP_LINE ("            See the man entries for isalnum(3), etc. for a description")
REX_HELP_LINE ("            of these classes.  NOTE that these brackets are inner square")
REX_HELP_LINE ("            brackets and must appear inside the outer square brackets; e.g.,")
REX_HELP_LINE ("                        [^A-Z[:lower:]@#![:digit:]]")
REX_HELP_LINE ("            will NOT match upper- (\"A-Z\") or lower-case (\"[:lower:]\")")
REX_HELP_LINE ("            alphabetic characters, punctuation marks @, #, and ! (\"@#!\"),")
REX_HELP_LINE ("            or decimal digits (\"[:digit:]\").")
REX_HELP_LINE ("")
REX_HELP_LINE ("Special Character Sequences in Replacement Text:")
REX_HELP_LINE ("")
REX_HELP_LINE ("    \\M  $M")
REX_HELP_LINE ("    \\<M>  $<M>")
REX_HELP_LINE ("            insert subexpression M (in the range 1..N) matched by the RE;")
REX_HELP_LINE ("            enclose multi-digt numbers (10 and up) in angle brackets.")
REX_HELP_LINE ("    \\<name>")
REX_HELP_LINE ("    $<name> insert the named group if it was matched by the RE; enclose")
REX_HELP_LINE ("            names in angle brackets.")
REX_HELP_LINE ("    \\&  $&")
REX_HELP_LINE ("    \\0  $0  insert the entire text matched by the RE.")
REX_HELP_LINE ("    \\`  $`  insert the text preceding the match.")
REX_HELP_LINE ("    \\'  $'  insert the text following the match.")
REX_HELP_LINE ("    \\l...")
REX_HELP_LINE ("    $l...   insert the numbered or named group matched by the RE,")
REX_HELP_LINE ("            converted to lower case.  For example, \"\\lM\", \"$l<M>\",")
REX_HELP_LINE ("            \"\\l<name>\", \"$l&\", and \"\\l`\".")
REX_HELP_LINE ("    \\u...")
REX_HELP_LINE ("    $u...   insert the numbered or named group matched by the RE,")
REX_HELP_LINE ("            converted to upper case.  For example, \"$uM\", \"\\u<M>\",")
REX_HELP_LINE ("            \"$u<name>\", \"\\u&\", and \"$u'\".")
REX_HELP_LINE ("    \\c      insert character 'c' (e.g., \"\\$\" gives \"$\").")
