const char * INITBLOB0 =  " (define (caar x) (car (car x))) (define (cadr x) (car (cdr x))) (define (cdar x) (cdr (car x))) (define (cddr x) (cdr (cdr x))) (define (caaar x) (car (car (car x)))) (define (caadr x) (car (car (cdr x)))) (define (cadar x) (car (cdr (car x)))) (define (caddr x) (car (cdr (cdr x)))) (define (cdaar x) (cdr (car (car x)))) (define (cdadr x) (cdr (car (cdr x)))) (define (cddar x) (cdr (cdr (car x)))) (define (cdddr x) (cdr (cdr (cdr x)))) (define (caaaar x) (car (car (car (car x))))) (define (caaadr x) (car (car (car (cdr x))))) (define (caadar x) (car (car (cdr (car x))))) (define (caaddr x) (car (car (cdr (cdr x))))) (define (cadaar x) (car (cdr (car (car x))))) (define (cadadr x) (car (cdr (car (cdr x))))) (define (caddar x) (car (cdr (cdr (car x))))) (define (cadddr x) (car (cdr (cdr (cdr x))))) (define (cdaaar x) (cdr (car (car (car x))))) (define (cdaadr x) (cdr (car (car (cdr x))))) (define (cdadar x) (cdr (car (cdr (car x))))) (define (cdaddr x) (cdr (car (cdr (cdr x))))) (define (cddaar x) (cdr (cdr (car (car x))))) (define (cddadr x) (cdr (cdr (car (cdr x))))) (define (cdddar x) (cdr (cdr (cdr (car x))))) (define (cddddr x) (cdr (cdr (cdr (cdr x))))) " ;
const char * INITBLOB1 =  " (define (macro-expand form) ((eval (get-closure-code (eval (car form)))) form)) " ;
const char * INITBLOB2 =  " (define (macro-expand-all form) (if (macro? form) (macro-expand-all (macro-expand form)) form)) " ;
const char * INITBLOB3 =  " (define *compile-hook* macro-expand-all) " ;
const char * INITBLOB4 =  " (macro (unless form) `(if (not ,(cadr form)) (begin ,@(cddr form)))) " ;
const char * INITBLOB5 =  " (macro (when form) `(if ,(cadr form) (begin ,@(cddr form)))) " ;
const char * INITBLOB6 =  " (macro (define-macro dform) (if (symbol? (cadr dform)) `(macro ,@(cdr dform)) (let ((form (gensym))) `(macro (,(caadr dform) ,form) (apply (lambda ,(cdadr dform) ,@(cddr dform)) (cdr ,form)))))) " ;
const char * INITBLOB7 =  " (define exact? integer?) (define (inexact? x) (and (real? x) (not (integer? x)))) (define (even? n) (= (remainder n 2) 0)) (define (odd? n) (not (= (remainder n 2) 0))) (define (zero? n) (= n 0)) (define (positive? n) (> n 0)) (define (negative? n) (< n 0)) (define complex? number?) (define rational? real?) (define (abs n) (if (>= n 0) n (- n))) (define (exact->inexact n) (* n 1.0)) (define (<> n1 n2) (not (= n1 n2))) " ;
const char * INITBLOB8 =  " (define (max . lst) (foldr (lambda (a b) (if (> a b) (if (exact? b) a (+ a 0.0)) (if (exact? a) b (+ b 0.0)))) (car lst) (cdr lst))) (define (min . lst) (foldr (lambda (a b) (if (< a b) (if (exact? b) a (+ a 0.0)) (if (exact? a) b (+ b 0.0)))) (car lst) (cdr lst))) " ;
const char * INITBLOB9 =  " (define (succ x) (+ x 1)) (define (pred x) (- x 1)) (define gcd (lambda a (if (null? a) 0 (let ((aa (abs (car a))) (bb (abs (cadr a)))) (if (= bb 0) aa (gcd bb (remainder aa bb))))))) (define lcm (lambda a (if (null? a) 1 (let ((aa (abs (car a))) (bb (abs (cadr a)))) (if (or (= aa 0) (= bb 0)) 0 (abs (* (quotient aa (gcd aa bb)) bb))))))) " ;
const char * INITBLOB10 =  " (define (string . charlist) (list->string charlist)) " ;
const char * INITBLOB11 =  " (define (list->string charlist) (let* ((len (length charlist)) (newstr (make-string len)) (fill-string! (lambda (str i len charlist) (if (= i len) str (begin (string-set! str i (car charlist)) (fill-string! str (+ i 1) len (cdr charlist))))))) (fill-string! newstr 0 len charlist))) " ;
const char * INITBLOB12 =  " (define (string-fill! s e) (let ((n (string-length s))) (let loop ((i 0)) (if (= i n) s (begin (string-set! s i e) (loop (succ i))))))) " ;
const char * INITBLOB13 =  " (define (string->list s) (let loop ((n (pred (string-length s))) (l '())) (if (= n -1) l (loop (pred n) (cons (string-ref s n) l))))) " ;
const char * INITBLOB14 =  " (define (string-copy str) (string-append str)) " ;
const char * INITBLOB15 =  " (define (string->anyatom str pred) (let* ((a (string->atom str))) (if (pred a) a (error \"string->xxx: not a xxx\" a)))) " ;
const char * INITBLOB16 =  " (define (string->number str . base) (let ((n (string->atom str (if (null? base) 10 (car base))))) (if (number? n) n #f))) " ;
const char * INITBLOB17 =  " (define (anyatom->string n pred) (if (pred n) (atom->string n) (error \"xxx->string: not a xxx\" n))) " ;
const char * INITBLOB18 =  " (define (number->string n . base) (atom->string n (if (null? base) 10 (car base)))) " ;
const char * INITBLOB19 =  " (define (char-cmp? cmp a b) (cmp (char->integer a) (char->integer b))) (define (char-ci-cmp? cmp a b) (cmp (char->integer (char-downcase a)) (char->integer (char-downcase b)))) " ;
const char * INITBLOB20 =  " (define (char=? a b) (char-cmp? = a b)) (define (char<? a b) (char-cmp? < a b)) (define (char>? a b) (char-cmp? > a b)) (define (char<=? a b) (char-cmp? <= a b)) (define (char>=? a b) (char-cmp? >= a b)) " ;
const char * INITBLOB21 =  " (define (char-ci=? a b) (char-ci-cmp? = a b)) (define (char-ci<? a b) (char-ci-cmp? < a b)) (define (char-ci>? a b) (char-ci-cmp? > a b)) (define (char-ci<=? a b) (char-ci-cmp? <= a b)) (define (char-ci>=? a b) (char-ci-cmp? >= a b)) " ;
const char * INITBLOB22 =  " (define (string-cmp? chcmp cmp a b) (let ((na (string-length a)) (nb (string-length b))) (let loop ((i 0)) (cond ((= i na) (if (= i nb) (cmp 0 0) (cmp 0 1))) ((= i nb) (cmp 1 0)) ((chcmp = (string-ref a i) (string-ref b i)) (loop (succ i))) (else (chcmp cmp (string-ref a i) (string-ref b i))))))) " ;
const char * INITBLOB23 =  " (define (string=? a b) (string-cmp? char-cmp? = a b)) (define (string<? a b) (string-cmp? char-cmp? < a b)) (define (string>? a b) (string-cmp? char-cmp? > a b)) (define (string<=? a b) (string-cmp? char-cmp? <= a b)) (define (string>=? a b) (string-cmp? char-cmp? >= a b)) " ;
const char * INITBLOB24 =  " (define (string-ci=? a b) (string-cmp? char-ci-cmp? = a b)) (define (string-ci<? a b) (string-cmp? char-ci-cmp? < a b)) (define (string-ci>? a b) (string-cmp? char-ci-cmp? > a b)) (define (string-ci<=? a b) (string-cmp? char-ci-cmp? <= a b)) (define (string-ci>=? a b) (string-cmp? char-ci-cmp? >= a b)) " ;
const char * INITBLOB25 =  " (define (list . x) x) " ;
const char * INITBLOB26 =  " (define (foldr f x lst) (if (null? lst) x (foldr f (f x (car lst)) (cdr lst)))) " ;
const char * INITBLOB27 =  " (define (unzip1-with-cdr . lists) (unzip1-with-cdr-iterative lists '() '())) " ;
const char * INITBLOB28 =  " (define (unzip1-with-cdr-iterative lists cars cdrs) (if (null? lists) (cons cars cdrs) (let ((car1 (caar lists)) (cdr1 (cdar lists))) (unzip1-with-cdr-iterative (cdr lists) (append cars (list car1)) (append cdrs (list cdr1)))))) " ;
const char * INITBLOB29 =  " (define (map proc . lists) (if (null? lists) (apply proc) (if (null? (car lists)) '() (let* ((unz (apply unzip1-with-cdr lists)) (cars (car unz)) (cdrs (cdr unz))) (cons (apply proc cars) (apply map (cons proc cdrs))))))) " ;
const char * INITBLOB30 =  " (define (for-each proc . lists) (if (null? lists) (apply proc) (if (null? (car lists)) #t (let* ((unz (apply unzip1-with-cdr lists)) (cars (car unz)) (cdrs (cdr unz))) (apply proc cars) (apply map (cons proc cdrs)))))) " ;
const char * INITBLOB31 =  " (define (list-tail x k) (if (zero? k) x (list-tail (cdr x) (- k 1)))) " ;
const char * INITBLOB32 =  " (define (list-ref x k) (car (list-tail x k))) " ;
const char * INITBLOB33 =  " (define (last-pair x) (if (pair? (cdr x)) (last-pair (cdr x)) x)) " ;
const char * INITBLOB34 =  " (define (head stream) (car stream)) " ;
const char * INITBLOB35 =  " (define (tail stream) (force (cdr stream))) " ;
const char * INITBLOB36 =  " (define (vector-equal? x y) (and (vector? x) (vector? y) (= (vector-length x) (vector-length y)) (let ((n (vector-length x))) (let loop ((i 0)) (if (= i n) #t (and (equal? (vector-ref x i) (vector-ref y i)) (loop (succ i)))))))) " ;
const char * INITBLOB37 =  " (define (list->vector x) (apply vector x)) " ;
const char * INITBLOB38 =  " (define (vector-fill! v e) (let ((n (vector-length v))) (let loop ((i 0)) (if (= i n) v (begin (vector-set! v i e) (loop (succ i))))))) " ;
const char * INITBLOB39 =  " (define (vector->list v) (let loop ((n (pred (vector-length v))) (l '())) (if (= n -1) l (loop (pred n) (cons (vector-ref v n) l))))) " ;
const char * INITBLOB40 =  " (macro quasiquote (lambda (l) (define (mcons f l r) (if (and (pair? r) (eq? (car r) 'quote) (eq? (car (cdr r)) (cdr f)) (pair? l) (eq? (car l) 'quote) (eq? (car (cdr l)) (car f))) (if (or (procedure? f) (number? f) (string? f)) f (list 'quote f)) (if (eqv? l vector) (apply l (eval r)) (list 'cons l r) ))) (define (mappend f l r) (if (or (null? (cdr f)) (and (pair? r) (eq? (car r) 'quote) (eq? (car (cdr r)) '()))) l (list 'append l r))) (define (foo level form) (cond ((not (pair? form)) (if (or (procedure? form) (number? form) (string? form)) form (list 'quote form)) ) ((eq? 'quasiquote (car form)) (mcons form ''quasiquote (foo (+ level 1) (cdr form)))) (#t (if (zero? level) (cond ((eq? (car form) 'unquote) (car (cdr form))) ((eq? (car form) 'unquote-splicing) (error \"Unquote-splicing wasn't in a list:\" form)) ((and (pair? (car form)) (eq? (car (car form)) 'unquote-splicing)) (mappend form (car (cdr (car form))) (foo level (cdr form)))) (#t (mcons form (foo level (car form)) (foo level (cdr form))))) (cond ((eq? (car form) 'unquote) (mcons form ''unquote (foo (- level 1) (cdr form)))) ((eq? (car form) 'unquote-splicing) (mcons form ''unquote-splicing (foo (- level 1) (cdr form)))) (#t (mcons form (foo level (car form)) (foo level (cdr form))))))))) (foo 0 (car (cdr l))))) " ;
const char * INITBLOB41 =  " (define (shared-tail x y) (let ((len-x (length x)) (len-y (length y))) (define (shared-tail-helper x y) (if (eq? x y) x (shared-tail-helper (cdr x) (cdr y)))) (cond ((> len-x len-y) (shared-tail-helper (list-tail x (- len-x len-y)) y)) ((< len-x len-y) (shared-tail-helper x (list-tail y (- len-y len-x)))) (#t (shared-tail-helper x y))))) " ;
const char * INITBLOB42 =  " (unless (defined? 'dynamic-wind) (let ( (*active-windings* '()) (outer-env (current-environment))) (define before-func car) (define after-func cdr) (define make-winding cons) (define (activate-winding! new) ((before-func new)) (set! *active-windings* (cons new *active-windings*))) (define (deactivate-top-winding!) (let ((old-top (car *active-windings*))) (set! *active-windings* (cdr *active-windings*)) ((after-func old-top)))) (define (set-active-windings! new-ws) (unless (eq? new-ws *active-windings*) (let ((shared (shared-tail new-ws *active-windings*))) (define (pop-many) (unless (eq? *active-windings* shared) (deactivate-top-winding!) (pop-many))) (define (push-many new-ws) (unless (eq? new-ws shared) (push-many (cdr new-ws)) (activate-winding! (car new-ws)))) (pop-many) (push-many new-ws)))) (eval `(define call-with-current-continuation ,(let ((old-c/cc call-with-current-continuation)) (lambda (func) (old-c/cc (lambda (continuation) (func (let ((current-ws *active-windings*)) (lambda (x) (set-active-windings! current-ws) (continuation x))))))))) outer-env) (eval `(define dynamic-wind ,(lambda (before thunk after) (activate-winding! (make-winding before after)) (let ((result (thunk))) (deactivate-top-winding!) result))) outer-env))) " ;
const char * INITBLOB43 =  " (define call/cc call-with-current-continuation) " ;
const char * INITBLOB44 =  " (define (atom? x) (not (pair? x))) " ;
const char * INITBLOB45 =  " (define (equal? x y) (cond ((pair? x) (and (pair? y) (equal? (car x) (car y)) (equal? (cdr x) (cdr y)))) ((vector? x) (and (vector? y) (vector-equal? x y))) ((string? x) (and (string? y) (string=? x y))) (else (eqv? x y)))) " ;
const char * INITBLOB46 =  " (macro do (lambda (do-macro) (apply (lambda (do vars endtest . body) (let ((do-loop (gensym))) `(letrec ((,do-loop (lambda ,(map (lambda (x) (if (pair? x) (car x) x)) `,vars) (if ,(car endtest) (begin ,@(cdr endtest)) (begin ,@body (,do-loop ,@(map (lambda (x) (cond ((not (pair? x)) x) ((< (length x) 3) (car x)) (else (car (cdr (cdr x)))))) `,vars))))))) (,do-loop ,@(map (lambda (x) (if (and (pair? x) (cdr x)) (car (cdr x)) '())) `,vars))))) do-macro))) " ;
const char * INITBLOB47 =  " (define (generic-member cmp obj lst) (cond ((null? lst) #f) ((cmp obj (car lst)) lst) (else (generic-member cmp obj (cdr lst))))) " ;
const char * INITBLOB48 =  " (define (memq obj lst) (generic-member eq? obj lst)) (define (memv obj lst) (generic-member eqv? obj lst)) (define (member obj lst) (generic-member equal? obj lst)) " ;
const char * INITBLOB49 =  " (define (generic-assoc cmp obj alst) (cond ((null? alst) #f) ((cmp obj (caar alst)) (car alst)) (else (generic-assoc cmp obj (cdr alst))))) " ;
const char * INITBLOB50 =  " (define (assq obj alst) (generic-assoc eq? obj alst)) (define (assv obj alst) (generic-assoc eqv? obj alst)) (define (assoc obj alst) (generic-assoc equal? obj alst)) " ;
const char * INITBLOB51 =  " (define (acons x y z) (cons (cons x y) z)) " ;
const char * INITBLOB52 =  " (macro (define-with-return form) `(define ,(cadr form) (call/cc (lambda (return) ,@(cddr form))))) " ;
const char * INITBLOB53 =  " (define *handlers* (list)) " ;
const char * INITBLOB54 =  " (define (push-handler proc) (set! *handlers* (cons proc *handlers*))) " ;
const char * INITBLOB55 =  " (define (pop-handler) (let ((h (car *handlers*))) (set! *handlers* (cdr *handlers*)) h)) " ;
const char * INITBLOB56 =  " (define (more-handlers?) (pair? *handlers*)) " ;
const char * INITBLOB57 =  " (define (throw . x) (if (more-handlers?) (apply (pop-handler)) (apply error x))) " ;
const char * INITBLOB58 =  " (macro (catch form) (let ((label (gensym))) `(call/cc (lambda (exit) (push-handler (lambda () (exit ,(cadr form)))) (let ((,label (begin ,@(cddr form)))) (pop-handler) ,label))))) " ;
const char * INITBLOB59 =  " (define *error-hook* throw) " ;
const char * INITBLOB60 =  " (macro (make-environment form) `(apply (lambda () ,@(cdr form) (current-environment)))) " ;
const char * INITBLOB61 =  " (define-macro (eval-polymorphic x . envl) (display envl) (let* ((env (if (null? envl) (current-environment) (eval (car envl)))) (xval (eval x env))) (if (closure? xval) (make-closure (get-closure-code xval) env) xval))) " ;
const char * INITBLOB62 =  " (define *colon-hook* eval) " ;
const char * INITBLOB63 =  " (define (input-output-port? p) (and (input-port? p) (output-port? p))) " ;
const char * INITBLOB64 =  " (define (close-port p) (cond ((input-output-port? p) (close-input-port p) (close-output-port p)) ((input-port? p) (close-input-port p)) ((output-port? p) (close-output-port p)) (else (throw \"Not a port\" p)))) " ;
const char * INITBLOB65 =  " (define (call-with-input-file s p) (let ((inport (open-input-file s))) (if (eq? inport #f) #f (let ((res (p inport))) (close-input-port inport) res)))) " ;
const char * INITBLOB66 =  " (define (call-with-output-file s p) (let ((outport (open-output-file s))) (if (eq? outport #f) #f (let ((res (p outport))) (close-output-port outport) res)))) " ;
const char * INITBLOB67 =  " (define (with-input-from-file s p) (let ((inport (open-input-file s))) (if (eq? inport #f) #f (let ((prev-inport (current-input-port))) (set-input-port inport) (let ((res (p))) (close-input-port inport) (set-input-port prev-inport) res))))) " ;
const char * INITBLOB68 =  " (define (with-output-to-file s p) (let ((outport (open-output-file s))) (if (eq? outport #f) #f (let ((prev-outport (current-output-port))) (set-output-port outport) (let ((res (p))) (close-output-port outport) (set-output-port prev-outport) res))))) " ;
const char * INITBLOB69 =  " (define (with-input-output-from-to-files si so p) (let ((inport (open-input-file si)) (outport (open-input-file so))) (if (not (and inport outport)) (begin (close-input-port inport) (close-output-port outport) #f) (let ((prev-inport (current-input-port)) (prev-outport (current-output-port))) (set-input-port inport) (set-output-port outport) (let ((res (p))) (close-input-port inport) (close-output-port outport) (set-input-port prev-inport) (set-output-port prev-outport) res))))) " ;
const char * INITBLOB70 =  " (define *seed* 1) (define (random-next) (let* ((a 16807) (m 2147483647) (q (quotient m a)) (r (modulo m a))) (set! *seed* (- (* a (- *seed* (* (quotient *seed* q) q))) (* (quotient *seed* q) r))) (if (< *seed* 0) (set! *seed* (+ *seed* m))) *seed*)) (define *features* '(srfi-0 tinyscheme)) " ;
const char * INITBLOB71 =  " (define-macro (cond-expand . cond-action-list) (cond-expand-runtime cond-action-list)) " ;
const char * INITBLOB72 =  " (define (cond-expand-runtime cond-action-list) (if (null? cond-action-list) #t (if (cond-eval (caar cond-action-list)) `(begin ,@(cdar cond-action-list)) (cond-expand-runtime (cdr cond-action-list))))) " ;
const char * INITBLOB73 =  " (define (cond-eval-and cond-list) (foldr (lambda (x y) (and (cond-eval x) (cond-eval y))) #t cond-list)) " ;
const char * INITBLOB74 =  " (define (cond-eval-or cond-list) (foldr (lambda (x y) (or (cond-eval x) (cond-eval y))) #f cond-list)) " ;
const char * INITBLOB75 =  " (define (cond-eval condition) (cond ((symbol? condition) (if (member condition *features*) #t #f)) ((eq? condition #t) #t) ((eq? condition #f) #f) (else (case (car condition) ((and) (cond-eval-and (cdr condition))) ((or) (cond-eval-or (cdr condition))) ((not) (if (not (null? (cddr condition))) (error \"cond-expand : 'not' takes 1 argument\") (not (cond-eval (cadr condition))))) (else (error \"cond-expand : unknown operator\" (car condition))))))) " ;
const char * INITBLOB76 =  " (gc-verbose #f) " ;

scheme_load_string(&sc, INITBLOB0);
scheme_load_string(&sc, INITBLOB1);
scheme_load_string(&sc, INITBLOB2);
scheme_load_string(&sc, INITBLOB3);
scheme_load_string(&sc, INITBLOB4);
scheme_load_string(&sc, INITBLOB5);
scheme_load_string(&sc, INITBLOB6);
scheme_load_string(&sc, INITBLOB7);
scheme_load_string(&sc, INITBLOB8);
scheme_load_string(&sc, INITBLOB9);
scheme_load_string(&sc, INITBLOB10);
scheme_load_string(&sc, INITBLOB11);
scheme_load_string(&sc, INITBLOB12);
scheme_load_string(&sc, INITBLOB13);
scheme_load_string(&sc, INITBLOB14);
scheme_load_string(&sc, INITBLOB15);
scheme_load_string(&sc, INITBLOB16);
scheme_load_string(&sc, INITBLOB17);
scheme_load_string(&sc, INITBLOB18);
scheme_load_string(&sc, INITBLOB19);
scheme_load_string(&sc, INITBLOB20);
scheme_load_string(&sc, INITBLOB21);
scheme_load_string(&sc, INITBLOB22);
scheme_load_string(&sc, INITBLOB23);
scheme_load_string(&sc, INITBLOB24);
scheme_load_string(&sc, INITBLOB25);
scheme_load_string(&sc, INITBLOB26);
scheme_load_string(&sc, INITBLOB27);
scheme_load_string(&sc, INITBLOB28);
scheme_load_string(&sc, INITBLOB29);
scheme_load_string(&sc, INITBLOB30);
scheme_load_string(&sc, INITBLOB31);
scheme_load_string(&sc, INITBLOB32);
scheme_load_string(&sc, INITBLOB33);
scheme_load_string(&sc, INITBLOB34);
scheme_load_string(&sc, INITBLOB35);
scheme_load_string(&sc, INITBLOB36);
scheme_load_string(&sc, INITBLOB37);
scheme_load_string(&sc, INITBLOB38);
scheme_load_string(&sc, INITBLOB39);
scheme_load_string(&sc, INITBLOB40);
scheme_load_string(&sc, INITBLOB41);
scheme_load_string(&sc, INITBLOB42);
scheme_load_string(&sc, INITBLOB43);
scheme_load_string(&sc, INITBLOB44);
scheme_load_string(&sc, INITBLOB45);
scheme_load_string(&sc, INITBLOB46);
scheme_load_string(&sc, INITBLOB47);
scheme_load_string(&sc, INITBLOB48);
scheme_load_string(&sc, INITBLOB49);
scheme_load_string(&sc, INITBLOB50);
scheme_load_string(&sc, INITBLOB51);
scheme_load_string(&sc, INITBLOB52);
scheme_load_string(&sc, INITBLOB53);
scheme_load_string(&sc, INITBLOB54);
scheme_load_string(&sc, INITBLOB55);
scheme_load_string(&sc, INITBLOB56);
scheme_load_string(&sc, INITBLOB57);
scheme_load_string(&sc, INITBLOB58);
scheme_load_string(&sc, INITBLOB59);
scheme_load_string(&sc, INITBLOB60);
scheme_load_string(&sc, INITBLOB61);
scheme_load_string(&sc, INITBLOB62);
scheme_load_string(&sc, INITBLOB63);
scheme_load_string(&sc, INITBLOB64);
scheme_load_string(&sc, INITBLOB65);
scheme_load_string(&sc, INITBLOB66);
scheme_load_string(&sc, INITBLOB67);
scheme_load_string(&sc, INITBLOB68);
scheme_load_string(&sc, INITBLOB69);
scheme_load_string(&sc, INITBLOB70);
scheme_load_string(&sc, INITBLOB71);
scheme_load_string(&sc, INITBLOB72);
scheme_load_string(&sc, INITBLOB73);
scheme_load_string(&sc, INITBLOB74);
scheme_load_string(&sc, INITBLOB75);
scheme_load_string(&sc, INITBLOB76);