/* $Id: chafn_help.h,v 1.1 2025/03/10 04:12:22 alex Exp $ */
/*******************************************************************************

    chafn_help.h

    CHAFN Help Text.


    This is help text for the CHAFN program, displayed when the "-help"
    option is specified on the command line.

    The text is a sequence of character strings, each enclosed in a
    TEXT_H_LINE macro.  TEXT_H_LINE can be #define'd in various ways.
    To print out the help text on the user's console, CHAFN does the
    following (this is executable code):

        #define  TEXT_H_LINE(s)  fprintf (helpout, "%s\n", s) ;
        #include  "chafn_help.h"

    This produces a sequence of fprintf(3) statements that print each line.

    If TEXT_H_LINE is not #define'd, this header file generates an array of
    strings for the lines of text.

    In all cases, TEXT_H_LINE is #undef'ed at the end of the header file.
    An application must redefine TEXT_H_LINE if it needs to include this
    header file again in the same source file.

    The sequence of TEXT_H_LINE-enclosed strings is generated by the
    Makefile from "chafn_help.txt".  The sequence is written to
    "chafn_help.h.new", which can then replace -- manually via
    editing -- the sequence below in this version-controlled file.

*******************************************************************************/


#ifndef TEXT_H_LINE
	/* Construct a list of character strings for initializing an array. */
#    define  TEXT_H_LINE (s)  s,
#endif

TEXT_H_LINE ("---------")
TEXT_H_LINE ("I REPEAT:")
TEXT_H_LINE ("      To verify your changes before making them, first run CHAFN")
TEXT_H_LINE ("      with an initial \"-test\" option to show the results without")
TEXT_H_LINE ("      actually renaming the files:")
TEXT_H_LINE ("")
TEXT_H_LINE ("          % chafn -t ...\t(Test but do NOT perform changes)")
TEXT_H_LINE ("---------")
TEXT_H_LINE ("")
TEXT_H_LINE ("Regular-Expression Matching and Substitution:")
TEXT_H_LINE ("")
TEXT_H_LINE ("    % chafn [-all] [-max <substitutions>] <pattern> <replacement> <file(s)>")
TEXT_H_LINE ("")
TEXT_H_LINE ("        First two non-option arguments are the pattern and replacement,")
TEXT_H_LINE ("        respectively.  Do NOT use this mode of operation with the other")
TEXT_H_LINE ("        file name modification options below.")
TEXT_H_LINE ("")
TEXT_H_LINE ("Case Conversion:")
TEXT_H_LINE ("")
TEXT_H_LINE ("    % chafn -capitalize <file(s)>")
TEXT_H_LINE ("    % chafn -lower <file(s)>")
TEXT_H_LINE ("    % chafn -upper <file(s)>")
TEXT_H_LINE ("")
TEXT_H_LINE ("Translate Selected Characters to Other Characters:")
TEXT_H_LINE ("")
TEXT_H_LINE ("    % chafn -xlat <translation> <file(s)>")
TEXT_H_LINE ("")
TEXT_H_LINE ("        For example, a translation string of \"abcdef\" translates a->b,")
TEXT_H_LINE ("        c->d, and e->f.")
TEXT_H_LINE ("")
TEXT_H_LINE ("Convert Square/Curly Brackets to Parentheses:")
TEXT_H_LINE ("")
TEXT_H_LINE ("    % chafn -brackets <file(s)>")
TEXT_H_LINE ("")
TEXT_H_LINE ("Smart Characters Converted to Normal ASCII:")
TEXT_H_LINE ("")
TEXT_H_LINE ("    % chafn -smart <file(s)>")
TEXT_H_LINE ("")
TEXT_H_LINE ("Insert Text at the Beginning of the File Name:")
TEXT_H_LINE ("")
TEXT_H_LINE ("    % chafn -prefix <text> <file(s)>")
TEXT_H_LINE ("")
TEXT_H_LINE ("Append Text at the End of the File Name:")
TEXT_H_LINE ("")
TEXT_H_LINE ("    % chafn -suffix <text> <file(s)>")
TEXT_H_LINE ("")
TEXT_H_LINE ("Append/Replace File Version Number, \".%03d\":")
TEXT_H_LINE ("")
TEXT_H_LINE ("    % chafn [-increment <n>] -version <number> <file(s)>")
TEXT_H_LINE ("")
TEXT_H_LINE ("        The version number is incremented after each file name;")
TEXT_H_LINE ("        the default increment is 1.")
TEXT_H_LINE ("")
TEXT_H_LINE ("Audio File Name Modification:")
TEXT_H_LINE ("")
TEXT_H_LINE ("    % chafn -yphen <file(s)>    \"<track> <song>\"  =>  \"<track> - <song>\"")
TEXT_H_LINE ("    % chafn -Yphen <file(s)>    \"<track>-<song>\"  =>  \"<track> - <song>\"")
TEXT_H_LINE ("    % chafn -dot <file(s)>      \"<track>. <song>\" =>  \"<track> - <song>\"")
TEXT_H_LINE ("")
TEXT_H_LINE ("    % chafn [-increment <n>] -track <number> <file(s)>")
TEXT_H_LINE ("")
TEXT_H_LINE ("        Inserts \"<number> - \" at the beginning of file names.")
TEXT_H_LINE ("        Track numbers less than 10 have a leading 0; e.g., \"07 - \".")
TEXT_H_LINE ("        The track number is incremented after each file name;")
TEXT_H_LINE ("        the default increment is 1.")

/*******************************************************************************
    Undefine TEXT_H_LINE - don't delete this!
*******************************************************************************/

#undef  TEXT_H_LINE
