    "# $Id: rex_henry_spencer_tests.h,v 1.2 2023/05/25 02:44:49 alex Exp $",
    "#*******************************************************************************",
    "#",
    "#    Modified Henry Spencer's regexp(3) Test File",
    "#",
    "#    This is Henry Spencer's regexp(3) test file modified to use",
    "#    the RE syntax of my REX_UTIL package.",
    "#",
    "#    Each line is a test with 6 tab-separated fields:",
    "#",
    "#        <test#>\t- Test number.",
    "#        <find>\t\t- Regular expression.",
    "#        <text>\t\t- Text against which the RE is matched.",
    "#        <status>\t- Expected test status:",
    "#\t\t\t    'c' for RE compile error,",
    "#\t\t\t    'y' if the RE is matched in <text>,",
    "#\t\t\t    'n' if the RE is NOT matched in <text>.",
    "#        <source>\t- A string whose references to the match and the",
    "#\t\t\t  capture groups in the regular expression will be",
    "#\t\t\t  substituted with the matched text.",
    "#        <result>\t- Expected result of the substitution.",
    "#",
    "#    (NOTE that <source> is NOT used for a typical search and replace in",
    "#    <text>, but to test substitution.  The source string only makes use",
    "#    of the matched text and not the portions of <text> before and after",
    "#    the match.)",
    "#",
    "#    Henry Spencer's actual test file had 5 fields per line.  To make it",
    "#    easier to identify and correlate tests, I added a new field, the test",
    "#    number, to both (1) my modified tests and (2) the copy of Henry's",
    "#    original tests further down below.",
    "#",
    "#    A solitary hyphen (\"-\") for a field indicates that the field is",
    "#    not used in the test.  Tests whose REs should fail to compile",
    "#    have a <text> field of \"-\".  Tests which don't test substitution",
    "#    have <replace> and <result> fields of \"-\".",
    "#",
    "#    Exactly one tab separates adjacent fields.  Consequently, a tab",
    "#    at the very beginning of the line means <find> is an empty string",
    "#    (\"\"):",
    "#",
    "#        \"<test#>\\t\\t<text>\\t<status>\\t<replace>\\t<result>\"",
    "#",
    "#    Likewise, two consecutive tabs mean the in-between field is",
    "#    an empty string; for example, two tabs after the <find> field",
    "#    mean that <text> is an empty string:",
    "#",
    "#        \"<test#>\\t<find>\\t\\t<status>\\t<replace>\\t<result>\"",
    "#",
    "#    At the end of this file, you'll find Henry Spencer's original test",
    "#    file (commented out).",
    "#",
    "#*******************************************************************************",
    "#",
    "#    To compile this file into a test program:",
    "#",
    "#    Convert the file into an array of C strings using the following sed",
    "#    commands in the order given:",
    "#",
    "#        s|\\\\|\\\\\\\\|g\t-- Escape all backslashes in the file so that the",
    "#\t\t\t   C compiler inserts a literal backslash in the",
    "#\t\t\t   string,  \"\\\" => \"\\\\\".",
    "#        s|\"|\\\\\"|g\t-- Escape all double quotes in the file so that",
    "#\t\t\t   the C compiler can distinguish them from the",
    "#\t\t\t   double quotes that will begin and end the string.",
    "#        s|\t|\\\\t|g\t-- Convert all tabs to C's \"\\t\" specifier.  Either",
    "#        s|\\t|\\\\t|g\t   one of these commands will work.  The first has",
    "#\t\t\t   an actual tab character for the search string;",
    "#\t\t\t   the second has \"\\t\", which sed will treat as",
    "#\t\t\t   a tab character in the search string.",
    "#        s|\\f|\\\\f|g\t-- I like form feeds, so sue me!",
    "#        s|^|    \"|\t-- Indent and insert a double quote delimiter at",
    "#\t\t\t   the beginning of the string.",
    "#        s|$|\",|\t-- Append a double quote delimiter at the end of",
    "#\t\t\t   the string, plus a comma.",
    "#",
    "#    Insert the output into a C array of strings:",
    "#",
    "#        static  const  char  *HenrySpencersTestFile[] = {",
    "#        \"<first-line>\",",
    "#        ...,",
    "#        \"#        (2) Replaced all \\\"\\\\N\\\"s in 4th and 5th columns by \\\"$N\\\".\",",
    "#        ...,",
    "#        \"#65\\t((a))\\tabc\\ty\\t&-\\\\1-\\\\2\\ta-a-a\",",
    "#        ...,",
    "#        \"<last-line>\",",
    "#        NULL",
    "#        } ;",
    "#",
    "#    The comment line \"(2)\" is the escaped translation of this line in this",
    "#    file:",
    "#",
    "#        ==>#        (2) Replaced all \"\\N\"s in 4th and 5th columns by \"$N\".<==",
    "#",
    "#    The other line shown is the translation of one of Henry Spencer's tests;",
    "#    the 5 regions of space are the 5 tab characters separating the 6 fields:",
    "#",
    "#        ==>#65\t((a))\tabc\ty\t&-\\1-\\2\ta-a-a<==",
    "#",
    "#*******************************************************************************",
    "\f",
    "#*******************************************************************************",
    "#",
    "#        SIDENOTE:",
    "#",
    "#        Wow!  I had tested my regular expression package against Henry",
    "#        Spencer's test file--with appropriate changes made for my RE",
    "#        syntax--back in the early 1990s.  Somehow, my modified test",
    "#        file disappeared.  When I downloaded Henry Spencer's rexexp(3)",
    "#        package in 2018 to incorporate his test file in my TREX program",
    "#        (\"../tools/trex.c\"), I thought I was going to have to again go",
    "#        through his test file, line by line and character by character,",
    "#        to convert it to my RE sytax.",
    "#",
    "#        Then, on May 27, 2019 at about 12:40 A.M., I happened upon my",
    "#        heretofore missing test file in a long-forgotten subdirectory.",
    "#        Hooray!!!  A big load off my mind!  (Back in 1996, there was",
    "#        a discussion about regular expressions on the comp.lang.tcl",
    "#        USENET newsgroup and some kind soul had recommended my package.",
    "#        I assembled a mini-distribution of my LIBGPL library containing",
    "#        only the files needed by the REX_UTIL package and my test program",
    "#        that read and checked the modified test file.  The Tcl developers",
    "#        went ahead and used Henry Spencer's package anyway, but at least",
    "#        I now have the test file AND the test program that read the file!)",
    "#",
    "#    Here is Henry Spencer's regexp(3) test file modified to use the RE",
    "#    syntax of my REX_UTIL package.  My original REX_UTIL package used",
    "#    a different syntax, so the modifications were more extensive back",
    "#    in the 1990s.  In 2021, after experience with the Sigil EPUB editor's",
    "#    regular expressions, I changed the syntax to more closely match that",
    "#    used by Henry Spencer.  Consequently, the only modification required",
    "#    now was:",
    "#",
    "#        (1) Replaced all \"&\"s in the 4th column by \"\\&\".",
    "#",
    "#    Henry used \"&\" to refer to the full matched text and \"\\N\" to refer",
    "#    to the numbered, parenthesized capture groups.  I now use \"\\&\" and",
    "#    \"\\N\", respectively.",
    "#",
    "#    Test #122 is the character 'a' enclosed in 10 sets of nested parentheses.",
    "#    Henry's rexexp(3) code only allows 9 capture groups, \\1 through \\9, as",
    "#    did my original REX_UTIL package.  Consequently, the test is flagged as",
    "#    producing an RE compilation error ('c').  Since REX_UTIL now allows an",
    "#    unlimited number of capture groups (within reason), I changed the test",
    "#    to pass instead of reporting an error because the RE failed to fail to",
    "#    compile.",
    "#",
    "#*******************************************************************************",
    "\f",
    "1\tabc\tabc\ty\t\\&\tabc",
    "2\tabc\txbc\tn\t-\t-",
    "3\tabc\taxc\tn\t-\t-",
    "4\tabc\tabx\tn\t-\t-",
    "5\tabc\txabcy\ty\t\\&\tabc",
    "6\tabc\tababc\ty\t\\&\tabc",
    "7\tab*c\tabc\ty\t\\&\tabc",
    "8\tab*bc\tabc\ty\t\\&\tabc",
    "9\tab*bc\tabbc\ty\t\\&\tabbc",
    "10\tab*bc\tabbbbc\ty\t\\&\tabbbbc",
    "11\tab+bc\tabbc\ty\t\\&\tabbc",
    "12\tab+bc\tabc\tn\t-\t-",
    "13\tab+bc\tabq\tn\t-\t-",
    "14\tab+bc\tabbbbc\ty\t\\&\tabbbbc",
    "15\tab?bc\tabbc\ty\t\\&\tabbc",
    "16\tab?bc\tabc\ty\t\\&\tabc",
    "17\tab?bc\tabbbbc\tn\t-\t-",
    "18\tab?c\tabc\ty\t\\&\tabc",
    "19\t^abc$\tabc\ty\t\\&\tabc",
    "20\t^abc$\tabcc\tn\t-\t-",
    "21\t^abc\tabcc\ty\t\\&\tabc",
    "22\t^abc$\taabc\tn\t-\t-",
    "23\tabc$\taabc\ty\t\\&\tabc",
    "24\t^\tabc\ty\t\\&\t\t! 5th field is \"\"",
    "25\t$\tabc\ty\t\\&\t\t! 5th field is \"\"",
    "26\ta.c\tabc\ty\t\\&\tabc",
    "27\ta.c\taxc\ty\t\\&\taxc",
    "28\ta.*c\taxyzc\ty\t\\&\taxyzc",
    "29\ta.*c\taxyzd\tn\t-\t-",
    "30\ta[bc]d\tabc\tn\t-\t-",
    "31\ta[bc]d\tabd\ty\t\\&\tabd",
    "32\ta[b-d]e\tabd\tn\t-\t-",
    "33\ta[b-d]e\tace\ty\t\\&\tace",
    "34\ta[b-d]\taac\ty\t\\&\tac",
    "35\ta[-b]\ta-\ty\t\\&\ta-",
    "36\ta[b-]\ta-\ty\t\\&\ta-",
    "37\t[k]\tab\tn\t-\t-",
    "38\ta[b-a]\t-\tc\t-\t-",
    "39\ta[]b\t-\tc\t-\t-",
    "40\ta[\t-\tc\t-\t-",
    "41\ta]\ta]\ty\t\\&\ta]",
    "42\ta[]]b\ta]b\ty\t\\&\ta]b",
    "43\ta[^bc]d\taed\ty\t\\&\taed",
    "44\ta[^bc]d\tabd\tn\t-\t-",
    "45\ta[^-b]c\tadc\ty\t\\&\tadc",
    "46\ta[^-b]c\ta-c\tn\t-\t-",
    "47\ta[^]b]c\ta]c\tn\t-\t-",
    "48\ta[^]b]c\tadc\ty\t\\&\tadc",
    "49\tab|cd\tabc\ty\t\\&\tab",
    "50\tab|cd\tabcd\ty\t\\&\tab",
    "51\t()ef\tdef\ty\t\\&-\\1\tef-",
    "52\t()*\t-\tc\t-\t-",
    "53\t*a\t-\tc\t-\t-",
    "54\t^*\t-\tc\t-\t-",
    "55\t$*\t-\tc\t-\t-",
    "56\t(*)b\t-\tc\t-\t-",
    "57\t$b\tb\tn\t-\t-",
    "58\ta\\\t-\tc\t-\t-",
    "59\ta\\(b\ta(b\ty\t\\&-\\1\ta(b-",
    "60\ta\\(*b\tab\ty\t\\&\tab",
    "61\ta\\(*b\ta((b\ty\t\\&\ta((b",
    "62\ta\\\\b\ta\\b\ty\t\\&\ta\\b",
    "63\tabc)\t-\tc\t-\t-",
    "64\t(abc\t-\tc\t-\t-",
    "65\t((a))\tabc\ty\t\\&-\\1-\\2\ta-a-a",
    "66\t(a)b(c)\tabc\ty\t\\&-\\1-\\2\tabc-a-c",
    "67\ta+b+c\taabbabc\ty\t\\&\tabc",
    "68\ta**\t-\tc\t-\t-",
    "69\ta*?\t-\tc\t-\t-",
    "70\t(a*)*\t-\tc\t-\t-",
    "71\t(a*)+\t-\tc\t-\t-",
    "72\t(a|)*\t-\tc\t-\t-",
    "73\t(a*|b)*\t-\tc\t-\t-",
    "74\t(a+|b)*\tab\ty\t\\&-\\1\tab-b",
    "75\t(a+|b)+\tab\ty\t\\&-\\1\tab-b",
    "76\t(a+|b)?\tab\ty\t\\&-\\1\ta-a",
    "77\t[^ab]*\tcde\ty\t\\&\tcde",
    "78\t(^)*\t-\tc\t-\t-",
    "79\t(ab|)*\t-\tc\t-\t-",
    "80\t)(\t-\tc\t-\t-",
    "81\t\tabc\ty\t\\&\t\t! 1st and 5th fields are \"\"",
    "82\tabc\t\tn\t-\t-",
    "83\ta*\t\ty\t\\&\t\t! 2nd and 5th fields are \"\"",
    "84\tabcd\tabcd\ty\t\\&-&-\\\\\\&\tabcd-&-\\abcd",
    "85\ta(bc)d\tabcd\ty\t\\1-\\\\1-\\\\\\1\tbc-\\1-\\bc",
    "86\t([abc])*d\tabbbcd\ty\t\\&-\\1\tabbbcd-c",
    "87\t([abc])*bcd\tabcd\ty\t\\&-\\1\tabcd-a",
    "88\ta|b|c|d|e\te\ty\t\\&\te",
    "89\t(a|b|c|d|e)f\tef\ty\t\\&-\\1\tef-e",
    "90\t((a*|b))*\t-\tc\t-\t-",
    "91\tabcd*efg\tabcdefg\ty\t\\&\tabcdefg",
    "92\tab*\txabyabbbz\ty\t\\&\tab",
    "93\tab*\txayabbbz\ty\t\\&\ta",
    "94\t(ab|cd)e\tabcde\ty\t\\&-\\1\tcde-cd",
    "95\t[abhgefdc]ij\thij\ty\t\\&\thij",
    "96\t^(ab|cd)e\tabcde\tn\tx\\1y\txy",
    "97\t(abc|)ef\tabcdef\ty\t\\&-\\1\tef-",
    "98\t(a|b)c*d\tabcd\ty\t\\&-\\1\tbcd-b",
    "99\t(ab|ab*)bc\tabc\ty\t\\&-\\1\tabc-a",
    "100\ta([bc]*)c*\tabc\ty\t\\&-\\1\tabc-bc",
    "101\ta([bc]*)(c*d)\tabcd\ty\t\\&-\\1-\\2\tabcd-bc-d",
    "102\ta([bc]+)(c*d)\tabcd\ty\t\\&-\\1-\\2\tabcd-bc-d",
    "103\ta([bc]*)(c+d)\tabcd\ty\t\\&-\\1-\\2\tabcd-b-cd",
    "104\ta[bcd]*dcdcde\tadcdcde\ty\t\\&\tadcdcde",
    "105\ta[bcd]+dcdcde\tadcdcde\tn\t-\t-",
    "106\t(ab|a)b*c\tabc\ty\t\\&-\\1\tabc-ab",
    "107\t((a)(b)c)(d)\tabcd\ty\t\\1-\\2-\\3-\\4\tabc-a-b-d",
    "108\t[ -~]*\tabc\ty\t\\&\tabc",
    "109\t[ -~ -~]*\tabc\ty\t\\&\tabc",
    "110\t[ -~ -~ -~]*\tabc\ty\t\\&\tabc",
    "111\t[ -~ -~ -~ -~]*\tabc\ty\t\\&\tabc",
    "112\t[ -~ -~ -~ -~ -~]*\tabc\ty\t\\&\tabc",
    "113\t[ -~ -~ -~ -~ -~ -~]*\tabc\ty\t\\&\tabc",
    "114\t[ -~ -~ -~ -~ -~ -~ -~]*\tabc\ty\t\\&\tabc",
    "115\t[a-zA-Z_][a-zA-Z0-9_]*\talpha\ty\t\\&\talpha",
    "116\t^a(bc+|b[eh])g|.h$\tabh\ty\t\\&-\\1\tbh-",
    "117\t(bc+d$|ef*g.|h?i(j|k))\teffgz\ty\t\\&-\\1-\\2\teffgz-effgz-",
    "118\t(bc+d$|ef*g.|h?i(j|k))\tij\ty\t\\&-\\1-\\2\tij-ij-j",
    "119\t(bc+d$|ef*g.|h?i(j|k))\teffg\tn\t-\t-",
    "120\t(bc+d$|ef*g.|h?i(j|k))\tbcdd\tn\t-\t-",
    "121\t(bc+d$|ef*g.|h?i(j|k))\treffgz\ty\t\\&-\\1-\\2\teffgz-effgz-",
    "122\t((((((((((a))))))))))\tb\tn\t-\t-",
    "123\t(((((((((a)))))))))\ta\ty\t\\&\ta",
    "124\tmultiple words of text\tuh-uh\tn\t-\t-",
    "125\tmultiple words\tmultiple words, yeah\ty\t\\&\tmultiple words",
    "126\t(.*)c(.*)\tabcde\ty\t\\&-\\1-\\2\tabcde-ab-de",
    "127\t\\((.*), (.*)\\)\t(a, b)\ty\t(\\2, \\1)\t(b, a)",
    "\f",
    "#*******************************************************************************",
    "#",
    "#    Henry Spencer's Original Test File",
    "#",
    "#    Remove the \"#<test#>\\t\" in column 1 of each line to get the original file.",
    "#    (As noted at the beginning of this file, I added the test number field to",
    "#    make it easier to correlate my modified tests with the original tests.)",
    "#",
    "#*******************************************************************************",
    "#",
    "#1\tabc\tabc\ty\t&\tabc",
    "#2\tabc\txbc\tn\t-\t-",
    "#3\tabc\taxc\tn\t-\t-",
    "#4\tabc\tabx\tn\t-\t-",
    "#5\tabc\txabcy\ty\t&\tabc",
    "#6\tabc\tababc\ty\t&\tabc",
    "#7\tab*c\tabc\ty\t&\tabc",
    "#8\tab*bc\tabc\ty\t&\tabc",
    "#9\tab*bc\tabbc\ty\t&\tabbc",
    "#10\tab*bc\tabbbbc\ty\t&\tabbbbc",
    "#11\tab+bc\tabbc\ty\t&\tabbc",
    "#12\tab+bc\tabc\tn\t-\t-",
    "#13\tab+bc\tabq\tn\t-\t-",
    "#14\tab+bc\tabbbbc\ty\t&\tabbbbc",
    "#15\tab?bc\tabbc\ty\t&\tabbc",
    "#16\tab?bc\tabc\ty\t&\tabc",
    "#17\tab?bc\tabbbbc\tn\t-\t-",
    "#18\tab?c\tabc\ty\t&\tabc",
    "#19\t^abc$\tabc\ty\t&\tabc",
    "#20\t^abc$\tabcc\tn\t-\t-",
    "#21\t^abc\tabcc\ty\t&\tabc",
    "#22\t^abc$\taabc\tn\t-\t-",
    "#23\tabc$\taabc\ty\t&\tabc",
    "#24\t^\tabc\ty\t&\t\t! 5th field is \"\".",
    "#25\t$\tabc\ty\t&\t\t! 5th field is \"\".",
    "#26\ta.c\tabc\ty\t&\tabc",
    "#27\ta.c\taxc\ty\t&\taxc",
    "#28\ta.*c\taxyzc\ty\t&\taxyzc",
    "#29\ta.*c\taxyzd\tn\t-\t-",
    "#30\ta[bc]d\tabc\tn\t-\t-",
    "#31\ta[bc]d\tabd\ty\t&\tabd",
    "#32\ta[b-d]e\tabd\tn\t-\t-",
    "#33\ta[b-d]e\tace\ty\t&\tace",
    "#34\ta[b-d]\taac\ty\t&\tac",
    "#35\ta[-b]\ta-\ty\t&\ta-",
    "#36\ta[b-]\ta-\ty\t&\ta-",
    "#37\t[k]\tab\tn\t-\t-",
    "#38\ta[b-a]\t-\tc\t-\t-",
    "#39\ta[]b\t-\tc\t-\t-",
    "#40\ta[\t-\tc\t-\t-",
    "#41\ta]\ta]\ty\t&\ta]",
    "#42\ta[]]b\ta]b\ty\t&\ta]b",
    "#43\ta[^bc]d\taed\ty\t&\taed",
    "#44\ta[^bc]d\tabd\tn\t-\t-",
    "#45\ta[^-b]c\tadc\ty\t&\tadc",
    "#46\ta[^-b]c\ta-c\tn\t-\t-",
    "#47\ta[^]b]c\ta]c\tn\t-\t-",
    "#48\ta[^]b]c\tadc\ty\t&\tadc",
    "#49\tab|cd\tabc\ty\t&\tab",
    "#50\tab|cd\tabcd\ty\t&\tab",
    "#51\t()ef\tdef\ty\t&-\\1\tef-",
    "#52\t()*\t-\tc\t-\t-",
    "#53\t*a\t-\tc\t-\t-",
    "#54\t^*\t-\tc\t-\t-",
    "#55\t$*\t-\tc\t-\t-",
    "#56\t(*)b\t-\tc\t-\t-",
    "#57\t$b\tb\tn\t-\t-",
    "#58\ta\\\t-\tc\t-\t-",
    "#59\ta\\(b\ta(b\ty\t&-\\1\ta(b-",
    "#60\ta\\(*b\tab\ty\t&\tab",
    "#61\ta\\(*b\ta((b\ty\t&\ta((b",
    "#62\ta\\\\b\ta\\b\ty\t&\ta\\b",
    "#63\tabc)\t-\tc\t-\t-",
    "#64\t(abc\t-\tc\t-\t-",
    "#65\t((a))\tabc\ty\t&-\\1-\\2\ta-a-a",
    "#66\t(a)b(c)\tabc\ty\t&-\\1-\\2\tabc-a-c",
    "#67\ta+b+c\taabbabc\ty\t&\tabc",
    "#68\ta**\t-\tc\t-\t-",
    "#69\ta*?\t-\tc\t-\t-",
    "#70\t(a*)*\t-\tc\t-\t-",
    "#71\t(a*)+\t-\tc\t-\t-",
    "#72\t(a|)*\t-\tc\t-\t-",
    "#73\t(a*|b)*\t-\tc\t-\t-",
    "#74\t(a+|b)*\tab\ty\t&-\\1\tab-b",
    "#75\t(a+|b)+\tab\ty\t&-\\1\tab-b",
    "#76\t(a+|b)?\tab\ty\t&-\\1\ta-a",
    "#77\t[^ab]*\tcde\ty\t&\tcde",
    "#78\t(^)*\t-\tc\t-\t-",
    "#79\t(ab|)*\t-\tc\t-\t-",
    "#80\t)(\t-\tc\t-\t-",
    "#81\t\tabc\ty\t&\t! 1st and 5th fields are \"\".",
    "#82\tabc\t\tn\t-\t-",
    "#83\ta*\t\ty\t&\t\t! 2nd and 5th fields are \"\".",
    "#84\tabcd\tabcd\ty\t&-\\&-\\\\&\tabcd-&-\\abcd",
    "#85\ta(bc)d\tabcd\ty\t\\1-\\\\1-\\\\\\1\tbc-\\1-\\bc",
    "#86\t([abc])*d\tabbbcd\ty\t&-\\1\tabbbcd-c",
    "#87\t([abc])*bcd\tabcd\ty\t&-\\1\tabcd-a",
    "#88\ta|b|c|d|e\te\ty\t&\te",
    "#89\t(a|b|c|d|e)f\tef\ty\t&-\\1\tef-e",
    "#90\t((a*|b))*\t-\tc\t-\t-",
    "#91\tabcd*efg\tabcdefg\ty\t&\tabcdefg",
    "#92\tab*\txabyabbbz\ty\t&\tab",
    "#93\tab*\txayabbbz\ty\t&\ta",
    "#94\t(ab|cd)e\tabcde\ty\t&-\\1\tcde-cd",
    "#95\t[abhgefdc]ij\thij\ty\t&\thij",
    "#96\t^(ab|cd)e\tabcde\tn\tx\\1y\txy",
    "#97\t(abc|)ef\tabcdef\ty\t&-\\1\tef-",
    "#98\t(a|b)c*d\tabcd\ty\t&-\\1\tbcd-b",
    "#99\t(ab|ab*)bc\tabc\ty\t&-\\1\tabc-a",
    "#100\ta([bc]*)c*\tabc\ty\t&-\\1\tabc-bc",
    "#101\ta([bc]*)(c*d)\tabcd\ty\t&-\\1-\\2\tabcd-bc-d",
    "#102\ta([bc]+)(c*d)\tabcd\ty\t&-\\1-\\2\tabcd-bc-d",
    "#103\ta([bc]*)(c+d)\tabcd\ty\t&-\\1-\\2\tabcd-b-cd",
    "#104\ta[bcd]*dcdcde\tadcdcde\ty\t&\tadcdcde",
    "#105\ta[bcd]+dcdcde\tadcdcde\tn\t-\t-",
    "#106\t(ab|a)b*c\tabc\ty\t&-\\1\tabc-ab",
    "#107\t((a)(b)c)(d)\tabcd\ty\t\\1-\\2-\\3-\\4\tabc-a-b-d",
    "#108\t[ -~]*\tabc\ty\t&\tabc",
    "#109\t[ -~ -~]*\tabc\ty\t&\tabc",
    "#110\t[ -~ -~ -~]*\tabc\ty\t&\tabc",
    "#111\t[ -~ -~ -~ -~]*\tabc\ty\t&\tabc",
    "#112\t[ -~ -~ -~ -~ -~]*\tabc\ty\t&\tabc",
    "#113\t[ -~ -~ -~ -~ -~ -~]*\tabc\ty\t&\tabc",
    "#114\t[ -~ -~ -~ -~ -~ -~ -~]*\tabc\ty\t&\tabc",
    "#115\t[a-zA-Z_][a-zA-Z0-9_]*\talpha\ty\t&\talpha",
    "#116\t^a(bc+|b[eh])g|.h$\tabh\ty\t&-\\1\tbh-",
    "#117\t(bc+d$|ef*g.|h?i(j|k))\teffgz\ty\t&-\\1-\\2\teffgz-effgz-",
    "#118\t(bc+d$|ef*g.|h?i(j|k))\tij\ty\t&-\\1-\\2\tij-ij-j",
    "#119\t(bc+d$|ef*g.|h?i(j|k))\teffg\tn\t-\t-",
    "#120\t(bc+d$|ef*g.|h?i(j|k))\tbcdd\tn\t-\t-",
    "#121\t(bc+d$|ef*g.|h?i(j|k))\treffgz\ty\t&-\\1-\\2\teffgz-effgz-",
    "#122\t((((((((((a))))))))))\t-\tc\t-\t-",
    "#123\t(((((((((a)))))))))\ta\ty\t&\ta",
    "#124\tmultiple words of text\tuh-uh\tn\t-\t-",
    "#125\tmultiple words\tmultiple words, yeah\ty\t&\tmultiple words",
    "#126\t(.*)c(.*)\tabcde\ty\t&-\\1-\\2\tabcde-ab-de",
    "#127\t\\((.*), (.*)\\)\t(a, b)\ty\t(\\2, \\1)\t(b, a)",
